package com.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setCostPrice(java.math.BigDecimal costPrice) {
		set("cost_price", costPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getCostPrice() {
		return get("cost_price");
	}

	public M setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	public M setDiscountPrice(java.math.BigDecimal discountPrice) {
		set("discount_price", discountPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getDiscountPrice() {
		return get("discount_price");
	}

	public M setCreateById(java.lang.String createById) {
		set("create_by_id", createById);
		return (M)this;
	}
	
	public java.lang.String getCreateById() {
		return getStr("create_by_id");
	}

	public M setUpdateById(java.lang.String updateById) {
		set("update_by_id", updateById);
		return (M)this;
	}
	
	public java.lang.String getUpdateById() {
		return getStr("update_by_id");
	}

	public M setDecribition(java.lang.String decribition) {
		set("decribition", decribition);
		return (M)this;
	}
	
	public java.lang.String getDecribition() {
		return getStr("decribition");
	}

	public M setStartCount(java.lang.Double startCount) {
		set("start_count", startCount);
		return (M)this;
	}
	
	public java.lang.Double getStartCount() {
		return getDouble("start_count");
	}

	public M setSaleCount(java.lang.Integer saleCount) {
		set("sale_count", saleCount);
		return (M)this;
	}
	
	public java.lang.Integer getSaleCount() {
		return getInt("sale_count");
	}

	public M setMonthSaleCount(java.lang.Integer monthSaleCount) {
		set("month_sale_count", monthSaleCount);
		return (M)this;
	}
	
	public java.lang.Integer getMonthSaleCount() {
		return getInt("month_sale_count");
	}

	public M setMarketState(java.lang.Boolean marketState) {
		set("market_state", marketState);
		return (M)this;
	}
	
	public java.lang.Boolean getMarketState() {
		return get("market_state");
	}

}
