package com.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateById(java.lang.String createById) {
		set("create_by_id", createById);
		return (M)this;
	}
	
	public java.lang.String getCreateById() {
		return getStr("create_by_id");
	}

	public M setUpdateById(java.lang.String updateById) {
		set("update_by_id", updateById);
		return (M)this;
	}
	
	public java.lang.String getUpdateById() {
		return getStr("update_by_id");
	}

	public M setMemberId(java.lang.String memberId) {
		set("member_id", memberId);
		return (M)this;
	}
	
	public java.lang.String getMemberId() {
		return getStr("member_id");
	}

	public M setScore(java.lang.Double score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Double getScore() {
		return getDouble("score");
	}

	public M setDescribition(java.lang.String describition) {
		set("describition", describition);
		return (M)this;
	}
	
	public java.lang.String getDescribition() {
		return getStr("describition");
	}

	public M setProductId(java.lang.String productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.String getProductId() {
		return getStr("product_id");
	}

}
