package com.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateById(java.lang.String createById) {
		set("create_by_id", createById);
		return (M)this;
	}
	
	public java.lang.String getCreateById() {
		return getStr("create_by_id");
	}

	public M setUpdateById(java.lang.String updateById) {
		set("update_by_id", updateById);
		return (M)this;
	}
	
	public java.lang.String getUpdateById() {
		return getStr("update_by_id");
	}

	public M setMemberId(java.lang.String memberId) {
		set("member_id", memberId);
		return (M)this;
	}
	
	public java.lang.String getMemberId() {
		return getStr("member_id");
	}

	public M setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setTotalWeight(java.lang.Double totalWeight) {
		set("total_weight", totalWeight);
		return (M)this;
	}
	
	public java.lang.Double getTotalWeight() {
		return getDouble("total_weight");
	}

	public M setDistributionFee(java.math.BigDecimal distributionFee) {
		set("distribution_fee", distributionFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getDistributionFee() {
		return get("distribution_fee");
	}

	public M setBusinessId(java.lang.String businessId) {
		set("business_id", businessId);
		return (M)this;
	}
	
	public java.lang.String getBusinessId() {
		return getStr("business_id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setShippingDate(java.util.Date shippingDate) {
		set("shipping_date", shippingDate);
		return (M)this;
	}
	
	public java.util.Date getShippingDate() {
		return get("shipping_date");
	}

	public M setDistrbutionId(java.lang.String distrbutionId) {
		set("distrbution_id", distrbutionId);
		return (M)this;
	}
	
	public java.lang.String getDistrbutionId() {
		return getStr("distrbution_id");
	}

}
