package com.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMember<M extends BaseSysMember<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}
	
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}

	public M setDeposit(java.math.BigDecimal deposit) {
		set("deposit", deposit);
		return (M)this;
	}
	
	public java.math.BigDecimal getDeposit() {
		return get("deposit");
	}

	public M setHeadUrl(java.lang.String headUrl) {
		set("head_url", headUrl);
		return (M)this;
	}
	
	public java.lang.String getHeadUrl() {
		return getStr("head_url");
	}

	public M setWxOpenId(java.lang.String wxOpenId) {
		set("wx_open_id", wxOpenId);
		return (M)this;
	}
	
	public java.lang.String getWxOpenId() {
		return getStr("wx_open_id");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

}
