package com.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImages<M extends BaseImages<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		Date createDate = get("create_date");
		return createDate == null? new Date(): createDate;
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		Date updateDate = get("update_date");
		return updateDate == null? new Date(): updateDate;
	}

	public M setCreateById(java.lang.String createById) {
		set("create_by_id", createById);
		return (M)this;
	}
	
	public java.lang.String getCreateById() {
		return getStr("create_by_id");
	}

	public M setUpdateById(java.lang.String updateById) {
		set("update_by_id", updateById);
		return (M)this;
	}
	
	public java.lang.String getUpdateById() {
		return getStr("update_by_id");
	}

	public M setSize(java.lang.Integer size) {
		set("size", size);
		return (M)this;
	}
	
	public java.lang.Integer getSize() {
		return getInt("size");
	}

	public M setDistUrl(java.lang.String distUrl) {
		set("dist_url", distUrl);
		return (M)this;
	}
	
	public java.lang.String getDistUrl() {
		return getStr("dist_url");
	}

	public M setSourceId(java.lang.String sourceId) {
		set("source_id", sourceId);
		return (M)this;
	}
	
	public java.lang.String getSourceId() {
		return getStr("source_id");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public java.lang.String getContentType(){
		return getStr("content_type");
	}
	
	public M setContentType(java.lang.String contentType){
		set("content_type", contentType);
		return (M)this;
	}
}
