package com.jfinal.model;

import com.jfinal.model.base.BaseDistributionStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DistributionStation extends BaseDistributionStation<DistributionStation> {
	public static final DistributionStation dao = new DistributionStation().dao();
}
