package com.jfinal.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.jfinal.model.base.BaseImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
//解析json时忽略字段
@JsonIgnoreProperties(value={"updateById","createById","distUrl","sourceId","type"})
public class Images extends BaseImages<Images> {
	public static final Images dao = new Images().dao();
	
	public static final String productType = "0";
	
	public static final String advertisementType = "1"; 
	
	public String getRelativePath() {
		return getStr("relative_path");
	}

	public Images setRelativePath(String relativePath) {
		set("relative_path", relativePath);
		return this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public Images setName(String name) {
		set("name", name);
		return this;
	}
}
