package com.jfinal.model;

import com.jfinal.model.base.BaseOrderItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderItem extends BaseOrderItem<OrderItem> {
	public static final OrderItem dao = new OrderItem().dao();
}
