package com.jfinal.model;

import com.jfinal.model.base.BaseProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	public static final Product dao = new Product().dao();
	

	public boolean getDelState() {
		return getBoolean("del_state");
	}
	
	public Product setDelState(boolean delState) {
		set("del_state", delState);
		return this;
	}
	
}
