package com.jfinal.model;

import com.jfinal.model.base.BaseProdctSaleLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProdctSaleLog extends BaseProdctSaleLog<ProdctSaleLog> {
	public static final ProdctSaleLog dao = new ProdctSaleLog().dao();
}
