package com.jfinal.model;

import com.jfinal.model.base.BaseShipping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shipping extends BaseShipping<Shipping> {
	public static final Shipping dao = new Shipping().dao();
}
