package com.jfinal.model;

import com.jfinal.model.base.BaseSysMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMember extends BaseSysMember<SysMember> {
	public static final SysMember dao = new SysMember().dao();
}
